version: '3.7'

services:
  node:
    build: .
    container_name: ovh-availability-checker
    restart: unless-stopped
    volumes:
      - ./servers.json:/app/servers.json
    env_file: .env

volumes:
  logs:
